# Generated by Django 6.0.1 on 2026-01-16 08:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CASH_UZS', 'Cash UZS'), ('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('CASH_USD', 'Cash USD')], max_length=20)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], editable=False, max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField(blank=True)),
                ('balance_uzs', models.DecimalField(decimal_places=2, default=0, help_text='Amount agent owes us in UZS', max_digits=14)),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0, help_text='Amount agent owes us in USD', max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField(blank=True)),
                ('balance_uzs', models.DecimalField(decimal_places=2, default=0, help_text='Amount we owe supplier in UZS', max_digits=14)),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0, help_text='Amount we owe supplier in USD', max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ticket_type', models.CharField(choices=[('AIRTICKET', 'Airticket'), ('TOUR', 'Tour'), ('UMRA', 'Umra')], max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='USD', max_length=3)),
                ('total_purchase_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('sales_channel', models.CharField(choices=[('AGENT', 'Agent'), ('INDIVIDUAL', 'Individual')], max_length=20)),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='USD', max_length=3)),
                ('total_sold_price', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('profit_uzs', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('profit_usd', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('comment', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='agency.agent')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='agency.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3)),
                ('category', models.CharField(choices=[('SALE', 'Sale'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('AGENT_PAYMENT', 'Agent Payment'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='agency.account')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='agency.account')),
            ],
        ),
    ]
